server:
  port: 2004
api:
  version: v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_list_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    serialization:
      indent-output: true

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
jwt:
  expiryHour: 1
  expiryDay: 14
  secretKey: b0238cff00a72de79bebabb5b5d6a777ff4b5f0401e6518ea03d48262f4bd818
  refreshKey: 9106746cb1d349b31174dda29c2729d3448d9b8a57418cc1833c8478f0763980
  resetKey: 9106746cb1d349b31174dda29c2729d3448d9b8a57418cc1833c8478f0763980
openapi:
  service:
    api-docs: api-todo-list
    title: Todo List API
    version: ${api.version}
    description: This project is a simple yet powerful REST ful API for managing user lists, to-do lists and tasks.
    server: http://localhost:2004
    serverName: JavaTech
    license: Apache 2.0
    license-url: https://facebook.com/NongHoangVu04
